version: '3.9'

services:
  wordpress:
    image: wordpress:5.8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    volumes:
      - ../wegro-wp:/var/www/html
    networks:
      - app-network

  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish/conf/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - webserver
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ../wegro-wp:/var/www/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/conf:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
