version: "3.9"
services:
  proxy-server:
    image: jwilder/nginx-proxy
    container_name: proxy-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - wegro_development_network
    labels:
      - "com.github.nginx-proxy.nginx-proxy.ssl"
      - "com.github.nginx-proxy.nginx"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      - NGINX_PROXY_CONTAINER=proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - wegro_development_network
    depends_on:
      - proxy-server

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - wegro_development_network

  slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    links:
      - redis:redis-master
    volumes:
      - redis_data:/data
    networks:
      - wegro_development_network

  sentinel:
    build: sentinel
    image: wegro/sentinel:latest
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - redis:redis-master
      - slave
    networks:
      - wegro_development_network

  mysql-db:
    image: mysql:8.0.32
    container_name: mysql-database-8
    ports:
      - "3336:3306"
    volumes:
      - wegro_mysql_db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_wegro_password
      MYSQL_DATABASE: wegro
      MYSQL_USER: wegro_user
      MYSQL_PASSWORD: wegro_password
    networks:
      - wegro_development_network

volumes:
  wegro_mysql_db:
    driver: local
  redis_data:

networks:
  wegro_development_network:
    name: wegro_development_network
